import { assetUrl } from "../asset-url.js";

export const menuMusicTracks = [
  assetUrl("./assets/audio/menu-loop.mp3"),
  assetUrl("./assets/audio/menu-loop-v2.mp3"),
];

export const soundPresets = {
  ui: {
    duration: 0.08,
    gain: 0.05,
    steps: [{ type: "triangle", frequency: 520, duration: 0.08 }],
  },
  shot: {
    duration: 0.58,
    layers: [
      {
        kind: "noise",
        delay: 0,
        duration: 0.075,
        attack: 0.003,
        release: 0.07,
        gain: 0.55,
        filter: { type: "highpass", frequency: 850, q: 0.7 },
      },
      {
        kind: "tone",
        type: "sawtooth",
        frequency: 210,
        endFrequency: 95,
        delay: 0,
        duration: 0.24,
        attack: 0.005,
        release: 0.2,
        gain: 0.22,
      },
      {
        kind: "tone",
        type: "sine",
        frequency: 92,
        endFrequency: 48,
        delay: 0,
        duration: 0.46,
        attack: 0.008,
        release: 0.4,
        gain: 0.45,
      },
      {
        kind: "noise",
        delay: 0.025,
        duration: 0.555,
        attack: 0.012,
        release: 0.48,
        gain: 0.18,
        filter: { type: "lowpass", frequency: 420, q: 0.6 },
      },
    ],
  },
  miss: {
    duration: 0.55,
    layers: [
      {
        kind: "noise",
        delay: 0.1,
        duration: 0.45,
        attack: 0.008,
        release: 0.38,
        gain: 0.2,
        filter: { type: "bandpass", frequency: 900, q: 0.8 },
      },
      {
        kind: "tone",
        type: "sine",
        frequency: 280,
        endFrequency: 120,
        delay: 0.13,
        duration: 0.34,
        attack: 0.015,
        release: 0.28,
        gain: 0.09,
      },
    ],
  },
  hit: {
    duration: 0.7,
    layers: [
      {
        kind: "noise",
        delay: 0.1,
        duration: 0.12,
        attack: 0.003,
        release: 0.1,
        gain: 0.36,
        filter: { type: "highpass", frequency: 600, q: 0.9 },
      },
      {
        kind: "tone",
        type: "triangle",
        frequency: 620,
        endFrequency: 170,
        delay: 0.1,
        duration: 0.2,
        attack: 0.004,
        release: 0.17,
        gain: 0.16,
      },
      {
        kind: "noise",
        delay: 0.12,
        duration: 0.48,
        attack: 0.008,
        release: 0.4,
        gain: 0.32,
        filter: { type: "lowpass", frequency: 780, q: 0.7 },
      },
      {
        kind: "tone",
        type: "sine",
        frequency: 105,
        endFrequency: 58,
        delay: 0.12,
        duration: 0.5,
        attack: 0.01,
        release: 0.42,
        gain: 0.27,
      },
      {
        kind: "noise",
        delay: 0.2,
        duration: 0.5,
        attack: 0.01,
        release: 0.44,
        gain: 0.12,
        filter: { type: "bandpass", frequency: 1100, q: 0.6 },
      },
    ],
  },
  sunk: {
    duration: 1.4,
    layers: [
      {
        kind: "noise",
        delay: 0.1,
        duration: 0.48,
        attack: 0.004,
        release: 0.42,
        gain: 0.45,
        filter: { type: "lowpass", frequency: 850, q: 0.8 },
      },
      {
        kind: "tone",
        type: "sine",
        frequency: 95,
        endFrequency: 42,
        delay: 0.1,
        duration: 0.78,
        attack: 0.008,
        release: 0.68,
        gain: 0.4,
      },
      {
        kind: "tone",
        type: "triangle",
        frequency: 360,
        endFrequency: 92,
        delay: 0.1,
        duration: 0.35,
        attack: 0.004,
        release: 0.3,
        gain: 0.16,
      },
      {
        kind: "noise",
        delay: 0.32,
        duration: 0.45,
        attack: 0.004,
        release: 0.39,
        gain: 0.38,
        filter: { type: "bandpass", frequency: 520, q: 0.9 },
      },
      {
        kind: "tone",
        type: "sawtooth",
        frequency: 180,
        endFrequency: 70,
        delay: 0.32,
        duration: 0.45,
        attack: 0.006,
        release: 0.38,
        gain: 0.18,
      },
      {
        kind: "tone",
        type: "triangle",
        frequency: 150,
        endFrequency: 42,
        delay: 0.48,
        duration: 0.82,
        attack: 0.02,
        release: 0.7,
        gain: 0.17,
      },
      {
        kind: "noise",
        delay: 0.48,
        duration: 0.92,
        attack: 0.02,
        release: 0.8,
        gain: 0.17,
        filter: { type: "lowpass", frequency: 1600, q: 0.5 },
      },
      {
        kind: "tone",
        type: "sine",
        frequency: 62,
        endFrequency: 34,
        delay: 0.55,
        duration: 0.85,
        attack: 0.025,
        release: 0.74,
        gain: 0.26,
      },
    ],
  },
  victory: {
    duration: 0.88,
    gain: 0.09,
    steps: [
      { type: "triangle", frequency: 392, duration: 0.18 },
      { type: "triangle", frequency: 494, duration: 0.18 },
      { type: "triangle", frequency: 587, duration: 0.24 },
      { type: "sine", frequency: 784, duration: 0.28 },
    ],
  },
  defeat: {
    duration: 0.9,
    gain: 0.08,
    steps: [
      { type: "triangle", frequency: 330, duration: 0.2 },
      { type: "triangle", frequency: 247, duration: 0.22 },
      { type: "sine", frequency: 196, duration: 0.48 },
    ],
  },
  turn: {
    duration: 0.18,
    gain: 0.055,
    steps: [
      { type: "sine", frequency: 330, duration: 0.09 },
      { type: "sine", frequency: 440, duration: 0.09 },
    ],
  },
  roomReady: {
    duration: 0.46,
    gain: 0.07,
    steps: [
      { type: "triangle", frequency: 440, duration: 0.14 },
      { type: "triangle", frequency: 660, duration: 0.14 },
      { type: "sine", frequency: 880, duration: 0.18 },
    ],
  },
};

export const musicPreset = {
  loop: true,
  gain: 0.035,
  notes: [
    { frequency: 196, duration: 0.42 },
    { frequency: 247, duration: 0.42 },
    { frequency: 294, duration: 0.56 },
    { frequency: 247, duration: 0.42 },
    { frequency: 220, duration: 0.42 },
    { frequency: 262, duration: 0.56 },
    { frequency: 330, duration: 0.84 },
  ],
};

export function isKnownSound(name) {
  return Object.hasOwn(soundPresets, name);
}
